### PR TITLE
Add watchdog

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso this is ready for review, but I'm still working on the integration test

Note

- there is a question in the watchdog file. Search for `TODO` to find it
- one of the tests was disabled because the timings were off (other tests were interfering and causing it to fail)

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso this is now ready to be merged if it passes review ... but it will need a squashing before being merged :)

**Comment by ahmedalsudani** [comment]
To test Viewer integration, I suggest using https://github.com/Rise-Vision/rise-launcher-electron/tree/staging/watchdog. 

I checked what happens when watchdog stops receiving pings from Viewer by going into the console and typing `window.$riseWatchdog.send = null`

**Comment by tejohnso** [comment]
@fjvallarino Fixed up and tested on win/linux - ready for review

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
