### PR TITLE
Log serial number to BQ

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@tejohnso I've been testing this on VB Windows 10 machine but can't seem to get a value returned for `serial_number` in the Player_Data.configuration logs for my display. %APPDATA% on Windows is AppData/Roaming and I've tried placing the *bookpc/.serial-number* directory/file there as well as in AppData and AppData/Local but no success. 

Can you review and see any reason why this wouldn't work? Is there a way I can debug this somehow bearing in mind I develop on a Mac and can't build a local installer for myself. Thanks

**Comment by tejohnso** [comment]
@stulees you can use the windows delivery dev boxes on Sc to test a build that was staged via CCI build.

**Comment by tejohnso** [comment]
@stulees your catch shouldn't be silent.  Log.debug at least.

**Comment by stulees** [comment]
@tejohnso Please review again (last two commits), thanks

**Comment by tejohnso** [comment]
:+1:

**Comment by stulees** [comment]
@tejohnso FYI last commit removes the `.` prefix, file name is now *serial-number*

**Pull request merged**
