### PR TITLE
Include cec path on Windows

### PR DESCRIPTION
**Pull request by tejohnso**
Users will have to download and install the driver into the default
path.

### CODE REVIEW

**Comment by tejohnso** [comment]
@stulees @santiagonoguez updated to prevent multiple path entries and us env var for "program files" dir.

**Comment by stulees** [comment]
@tejohnso 👍

**Comment by santiagonoguez** [comment]
Also thumbs up ! I learned some interesting things by studying this code.

**Comment by santiagonoguez** [comment]
cool, this is more readable !

**Pull request merged**
