### PR TITLE
Copy scripts

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso 

This copies the script files properly, but for some reason, `initial-run.sh` is not having its executable permission preserved. Not sure if this PR is to blame

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
`initial-run.sh` has been fixed

**Comment by fjvallarino** [comment]
:+1:

**Comment by tejohnso** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso updated

**Pull request merged**
