### PR TITLE
Handle error type as text to avoid issues with Exceptions' properties not being enumerable

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
:+1: 

@fjvallarino was there an issue with the previous approach?

**Comment by fjvallarino** [comment]
@ahmedalsudani yeah, Errors do not have enumerable properties, so their content was being dropped (only "Exception" or "Rejection" was being logged)

**Comment by ahmedalsudani** [comment]
I see

**Pull request merged**
