### PR TITLE
Correct uninstall version folder and ps1 target

### PR DESCRIPTION
**Pull request by tejohnso**
@ahmedalsudani @fjvallarino please review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@tejohnso didn't notice that `start.bat` wasn't modified in the last PR. Can you add the execution policy parameter to `start.bat`?

**Comment by tejohnso** [comment]
@ahmedalsudani updated

**Comment by ahmedalsudani** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
