### PR TITLE
Release branch

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino @ahmedalsudani Ready to merge release branch

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani I thought we were going to provide artifacts from this branch, have CS test then and only then merge to master.

**Comment by ahmedalsudani** [comment]
@fjvallarino don't we usually send master to CS for testing?

**Comment by tejohnso** [comment]
@fjvallarino Master still isn't going to production so it doesn't matter at this point.  We'd have to rename this branch to get a staging build. Let's do it that way since it's more in line with master == production.

**Comment by fjvallarino** [comment]
@ahmedalsudani We did that in the past, but I think we should follow the "master equals production" rule.

**Comment by ahmedalsudani** [comment]
@fjvallarino Fair enough. Let's do it the right way :v:

**Pull request closed without merging**
