### PR TITLE
Stop running components before removing folders

### PR DESCRIPTION
**Pull request by tejohnso**
@fjvallarino This is going to fail because stopViewer doesn't exist.  

But I think we should have a general stopAll() that we can call instead of calling 4 different  methods

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso please review

**Comment by tejohnso** [comment]
Should we get rid of launcher.stopPlayer and launcher.stopCache since we now have a killJava

**Comment by fjvallarino** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
