### PR TITLE
Add version directory to scripts

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso ready for review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Comment by tejohnso** [comment]
@ahmedalsudani The start script should pass through any command line parameters to the installer invocation.

**Comment by ahmedalsudani** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
