### PR TITLE
Remove Viewer Cache before running / Fix Ubuntu Autostart

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso modified as discussed this morning. (deletion happens in shell files)

### CODE REVIEW

**Comment by fjvallarino** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso updated. This PR fixes both the viewer caching issue and Ubuntu autostart since both the Electron cache and lockfile are stored in the same directory -- which we now delete in start.sh/start.bat

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
