### PR TITLE
Kill explorer.exe on Windows (except on 7) before starting Player

### PR DESCRIPTION
**Pull request by fjvallarino**
Kill explorer.exe on Windows (except on 7) before starting Player, to avoid issues with touchscreen right swipe bringing up Action Center

@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by tejohnso** [comment]
@fjvallarino This shouldn't only be for unattended from my understanding.  If a user starts the player manually they still need to prevent tampering.  

The message should use the ui/messages module and have its own .md file.  I think we're going to need a more descriptive message but we can clarify that later.

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani updated to have explorer.exe killed on manual launcher invocations.

The message was not moved into its own Markdown module since it's part of a UI slide that may need specific styling; we are already doing something similar for the initial and proxy slides. In case you think we should change it, maybe discussing on a Hangout would be easier.

**Comment by tejohnso** [comment]
@fjvallarino One more thing....can you add a --skip-timeout for manual testing scenarios as well as E2E?

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
