### PR TITLE
Start remove-previous in the background on Windows

### PR DESCRIPTION
**Pull request by ahmedalsudani**

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso I saw a spawn timeout in the BQ logs, and this should fix it

**Comment by tejohnso** [comment]
:+1:   
Cleaning up dozens of /temp/rvplayer... dirs takes a long time for us because we have (had) so many.

**Comment by fjvallarino** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
Closing because this fix didn't work

**Pull request closed without merging**
