### PR TITLE
Add unattended flag to autostart menu option

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
@fjvallarino did that jshint flag not work for you?  The **esnext** flag is deprecated.

**Comment by fjvallarino** [comment]
@tejohnso I know, it's just that Sublime Text does not recognize it. I guess it's better if I change it locally.

**Comment by fjvallarino** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
