### PR TITLE
Global error catch should only log to file, not to UI (the UI part is handled by upper layers)

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
:+1: :tada: let's do this

**Comment by tejohnso** [comment]
How do we know for certain that all other errors do log to the UI?  If this is for unexpected errors, it seems it means it won't have been caught elsewhere.

**Comment by ahmedalsudani** [comment]
:+1: on board with this too

**Comment by tejohnso** [comment]
:+1:

**Comment by tejohnso** [comment]
@ahmedalsudani @fjvallarino I added a commit to prevent the rest of the actions from continuing if the prereqs fail.  Haven't tested it throughly yet.

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani This version works fine; I tested network checks, CAP and App Monitor. I also tested disconnecting Internet while components are being downloaded. In that scenario, we are showing this message: "Error downloading componentName.tar.gz. Please try again or post a question to http://community.risevision.com.". Is that correct? Do we want to tell the user which component failed or just saying we were not able to download component/update would be enough? I'm not sure we want to display that kind of detail to users (it may confusing).

**Comment by tejohnso** [comment]
I think that's OK.  I think it's a sensible error and it's going to go away once we complete the next epic anyway.

**Pull request merged**
