### PR TITLE
Use "then" method of text() response promise

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso please review

### CODE REVIEW

**Comment by tejohnso** [comment]
:+1:    Let's see what Alan and Hannah come up with

**Comment by fjvallarino** [comment]
@tejohnso I added two more commits. The one related to removing the installed versions is redundant, since we were already doing that for certain components (I'm not sure why Cache and Installer were not being removed); I think removing them unconditionally is better. The important change is the one related to creating a new temp folder for each installer run. Always using temp was the cause of having extraneous files in our install directory (since whatever we extracted previously was not removed).

**Comment by tejohnso** [comment]
:+1: Let's put it through testing

**Comment by fjvallarino** [comment]
@tejohnso rebased

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
