### PR TITLE
Add restart scripts, which avoid gracefully stopping Player

### PR DESCRIPTION
**Pull request by fjvallarino**
Add restart scripts, which avoid gracefully stopping Player (they are invoked inside Player at a point in time where the stop action is already graceful)

@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by tejohnso** [comment]
@fjvallarino Can you explain the "already graceful" part?

**Comment by fjvallarino** [comment]
@tejohnso It already logged to BQ that it is quitting

**Comment by tejohnso** [comment]
@fjvallarino @ahmedalsudani We're ok to merge this now?

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani :+1: for me, pending your approval

**Comment by ahmedalsudani** [comment]
:+1:

**Pull request merged**
