### PR TITLE
Add screenshot capture

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

A few comments:

- We are not sending anything when the capture/upload could not be performed
- I guess the screenshot capture should be retried
- We should think about an easier way to test messaging handlers. In this case, I mocked registerHandler to get an instance of what I wanted to test, but the condition function was left untested. Maybe adding some easily mockable method for simulating messages.
- This branch was just rebased from master; I'm not sure why the already existing commits were kept

### CODE REVIEW

**Comment by tejohnso** [comment]
@fjvallarino 

 - Why don't we have an integration test for `uploadBuffer` to confirm it gets into GCS as expected.  

 - Why not send a `screenshot-failed` message back from the handler if there was a problem?

**Comment by fjvallarino** [comment]
@tejohnso 

- The integration test was not added since I understood we were going to validate the complete process with an e2e test.
- I did not find a message with that name on the messaging server. Does it exist, or will the server relay any message a client sends it?

**Comment by tejohnso** [comment]
@fjvallarino 

 - Okay, we should cover that case with the e2e tests
 - There's no such message server-side at this point, but one should be added.  In the meantime you can send it.

**Comment by ahmedalsudani** [comment]
@fjvallarino good to merge once it's rebased and Tyler's comment is addressed.

**Comment by fjvallarino** [comment]
@tejohnso @ahmedalsudani updated

**Comment by ahmedalsudani** [comment]
:+1:

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
