### PR TITLE
Update proxy wording and highlight Verify/Save

### PR DESCRIPTION
**Pull request by tejohnso**
@ahmedalsudani please review
proxy

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@tejohnso I like the primary button change. I'm thinking we should move verify and safe to the left to go along with the convention in the rest of the Installer (the default "next step" button is always to the right)

**Comment by tejohnso** [comment]
@ahmedalsudani you mean move it to the right then?

**Comment by tejohnso** [comment]
@ahmedalsudani updated
proxy

**Comment by ahmedalsudani** [comment]
:+1: once R14 is merged

**Comment by tejohnso** [comment]
Deleting to PR onto master instead of R14

**Pull request closed without merging**
