### PR TITLE
Update version of Rise Cache

### PR DESCRIPTION
**Pull request by stulees**
- Fixes client receiving correct response every time
- New `financial/` endpoint with all CRUD operations

### CODE REVIEW

**Comment by stulees** [comment]
@tejohnso Please review, thanks. @fjvallarino FYI

**Comment by stulees** [comment]
@tejohnso @fjvallarino Failing on a UI test, *"validates autostart is false on display id setup"*. Thoughts?

**Comment by fjvallarino** [comment]
@stulees you have to modify package.json and set angular to "1.5.9" (fixed version, since 1.6.x breaks a few things). It seems a dependency update caused this.

@tejohnso FYI

**Comment by stulees** [comment]
@fjvallarino That didn't seem to work. Am I missing something?

**Comment by fjvallarino** [comment]
@stulees it did (integration tests pass now), but e2e are failing (it's a separate issue). I'm investigating

**Comment by stulees** [comment]
@fjvallarino okay thanks

**Comment by fjvallarino** [comment]
@stulees after retrying a few times, e2e tests passed.

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
