### PR TITLE
Add Quit hotkey

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso ready for review.

In order, we try:

- Ctrl + Shift + Q
- Ctrl + Shift + K
- Ctrl + Shift + F4

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso note the changes in the latest commit. For some reason, `platform.startProcess` was not being mocked on CCI even though there's a call for that https://github.com/Rise-Vision/rise-launcher-electron/pull/319/files#diff-b769d34041341ef404963402e9513651R342

**Comment by tejohnso** [comment]
@ahmedalsudani In addition to removing the timeout as discussed, you could try something like 

```javascript
["Q", "K", "F4"].some(setGlobalShortcut)
```
instead of a loop construct with a conditional premature exit

**Comment by ahmedalsudani** [comment]
@tejohnso updated

**Comment by tejohnso** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
