### PR TITLE
Respect unattended mode and improve message

### PR DESCRIPTION
**Pull request by tejohnso**

### CODE REVIEW

**Comment by fjvallarino** [comment]
@tejohnso Wouldn't calling sudo in unattended mode cause issues?

**Comment by tejohnso** [comment]
Yes.   At the time I was imagining the sudoers would be set up correctly but that is not likely and we don't want to have to add that requirement. 

Now I think we might be able to assume that an unattended call is happening on a machine that has already had the optimisations.  In that case we can exit.   Or maybe just skip the sudo operations and perform the others.

**Comment by tejohnso** [comment]
@fjvallarino please review latest changes

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
