### PR TITLE
Network check message has consistent width

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso the message was slowly creeping to the left because it's center-aligned, and its width is changing. In this PR, we append spaces to the end to preserve the width

### CODE REVIEW

**Comment by tejohnso** [comment]
@ahmedalsudani where does the magic number 6 come from?

**Comment by ahmedalsudani** [comment]
@tejohnso it's arbitrary. I kept going up from 3 until the pacing looked natural.

**Comment by tejohnso** [comment]
@ahmedalsudani I added a commit.  Ready when you are :+1:

**Comment by ahmedalsudani** [comment]
@tejohnso oops, thanks

**Pull request merged**
