### PR TITLE
Fix Installer Tip on how to stop player

### PR DESCRIPTION
**Pull request by jungeunyoon**

### CODE REVIEW

**Comment by jungeunyoon** [comment]
@santiagonoguez haha 👍 

@Rise-Vision/delivery Assuming this shouldn't be merged? Does this need to be scheduled in a release as well?

**Comment by jungeunyoon** [comment]
[(1) Installer Tip on how to stop player incorrect](https://trello.com/c/wPTeWfxW/3628-1-installer-tip-on-how-to-stop-player-incorrect)

**Comment by tejohnso** [comment]
Yeah this should be added to the list for next release.

**Comment by jungeunyoon** [comment]
@tejohnso 👍 Added, thanks.

**Pull request merged**
