### PR TITLE
Logging events around saving of GCS data

### PR DESCRIPTION
**Pull request by stulees**
- Now asynchronously creating local gcs data file so an error can be trapped
- Revised gcs integration tests to accommodate asyc behaviour

### CODE REVIEW

**Comment by stulees** [comment]
@tejohnso I get two gcs integration tests failing (locally) with these code changes and I can't figure out why they fail. Could you checkout my branch and take a look? Or advise a different way of going about this. Cheers

**Comment by tejohnso** [comment]
@stulees I pushed a corrected integration test file.  The main issue was that the test was setting mock gcs data at .gcs....json instead of ~/rvplayer/.gcs.....json

**Comment by stulees** [comment]
@tejohnso Thanks for that! How about the actual changes, approve?

**Comment by tejohnso** [comment]
:+1:

**Comment by stulees** [comment]
@tejohnso Please review last commit, thanks. @Rise-Vision/delivery FYI

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
