### PR TITLE
Remove no longer used config file entry

### PR DESCRIPTION
**Pull request by fjvallarino**
@tejohnso @ahmedalsudani please review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino I think we should keep this entry just in case we need to switch back to Chrome

**Comment by tejohnso** [comment]
@ahmedalsudani We can always create the browser entry from the proxy config if we need to.  In fact, we never really needed a separate entry for the browser because it can be mapped directly from the proxy config field.

**Comment by ahmedalsudani** [comment]
:+1:

**Comment by fjvallarino** [comment]
:+1:

**Pull request merged**
